name: HorseSkill
version: 1.1.0
author: stecool
main: com.github.StevenDesroches.HorseSkill.HorseSkill
api-version: 1.12.2
commands:
  horse:
    description: the basic horse command
    usage: /horse [claim, unclaim, summon]
permissions:
  HorseSkill.*:
    description: Gives access to everything
    default: true
    children:
      HorseSkill.commands.*: true
      HorseSkill.load: true
      HorseSkill.save: true
  HorseSkill.commands.*:
    description: Gives access to all the commands
    default: true
    children:
      HorseSkill.commands.claim: true
      HorseSkill.commands.unclaim: true
      HorseSkill.commands.summon: true
  HorseSkill.commands.claim:
    description: Gives the claim command
    default: true
  HorseSkill.commands.unclaim:
    description: Gives the unclaim command
    default: true
  HorseSkill.commands.summon:
    description: Gives the summon command
    default: true
  HorseSkill.load:
    description: Do player load his horse
    default: true
  HorseSkill.save:
    description: Do player save his horse
    default: true